export type ProjectCategory = "ระบบ" | "ข้อมูล" | "ครีเอทีฟ" | "กิจกรรม";

export type ProjectLink = {
  label: string;
  href: string;
};

export type Project = {
  slug: string;
  title: string;
  eyebrow: string;
  summary: string;
  category: ProjectCategory;
  year: string;
  role: string;
  accent: string;
  accent2: string;
  visual: "horplus" | "tiger" | "campus" | "tutor" | "cocolove" | "freelance" | "activity" | "robusgo" | "creator" | "production";
  highlights: string[];
  images?: string[];
  links?: ProjectLink[];
  featured?: boolean;
};

export const projects: Project[] = [
  {
    slug: "robusgo",
    title: "Robusgo",
    eyebrow: "I-New Gen Award 2025 · ปี 2",
    summary: "คิดสคริปต์และตัดต่อวิดีโอ เพื่อช่วยทีมวิศวะเล่าแนวคิดนวัตกรรมให้คนเข้าใจ",
    category: "ครีเอทีฟ",
    year: "SILVER",
    role: "สมาชิกทีม · Script & Video Editor",
    accent: "#60a5fa",
    accent2: "#a78bfa",
    visual: "robusgo",
    highlights: ["ทำงานร่วมกับทีมวิศวะ", "คิดและเรียบเรียงสคริปต์", "ตัดต่อวิดีโอนำเสนอ", "เหรียญเงินและ Popular Vote 2025"],
    images: [
      "/portfolio/robusgo/stage.webp",
      "/portfolio/robusgo/silver-award.webp",
      "/portfolio/robusgo/popular-vote.webp",
    ],
    links: [{ label: "ดูผลงานและรางวัล Robusgo", href: "https://www.facebook.com/share/p/1BsDzjmebu/" }],
    featured: true,
  },
  {
    slug: "horplus",
    title: "Horplus",
    eyebrow: "ระบบจัดการหอพัก · 2569",
    summary: "ส่งบิลค่าเช่า ค่าน้ำ และค่าไฟให้ผู้เช่าผ่าน LINE",
    category: "ระบบ",
    year: "2569",
    role: "ออกแบบและพัฒนาคนเดียว",
    accent: "#60a5fa",
    accent2: "#8b5cf6",
    visual: "horplus",
    highlights: ["วางโครงสร้างระบบ", "ออกแบบประสบการณ์ใช้งาน", "เชื่อมการส่งบิลผ่าน LINE"],
    images: [
      "/portfolio/horplus/dashboard.webp",
      "/portfolio/horplus/overview.webp",
      "/portfolio/horplus/rooms.webp",
      "/portfolio/horplus/billing.webp",
      "/portfolio/horplus/tenant-bill.webp",
    ],
    featured: true,
  },
  {
    slug: "nontsee",
    title: "Nontsee",
    eyebrow: "เว็บรอบรั้ว มก.ฉกส.",
    summary: "รวมหอพัก ร้านค้า และแผนที่รอบมหาวิทยาลัยไว้ในที่เดียว",
    category: "ระบบ",
    year: "SOLO",
    role: "ออกแบบและพัฒนาคนเดียว",
    accent: "#34d399",
    accent2: "#22d3ee",
    visual: "campus",
    highlights: ["จัดหมวดหมู่ข้อมูล", "ออกแบบแผนที่", "เปิดให้ผู้ใช้เพิ่มและแก้ไขสถานที่"],
    images: [
      "/portfolio/nontsee/home.webp",
      "/portfolio/nontsee/places.webp",
      "/portfolio/nontsee/map.webp",
      "/portfolio/nontsee/community.webp",
      "/portfolio/nontsee/contact.webp",
      "/portfolio/nontsee/install-ios.webp",
      "/portfolio/nontsee/install-android.webp",
      "/portfolio/nontsee/edit-place.webp",
      "/portfolio/nontsee/add-place.webp",
      "/portfolio/nontsee/android-guide.webp",
      "/portfolio/nontsee/qr.webp",
    ],
    links: [{ label: "เปิดใช้งาน Nontsee", href: "https://nontsee.glide.page/" }],
    featured: true,
  },
  {
    slug: "tiger-laundry",
    title: "TigerLaundry",
    eyebrow: "LINE Automation",
    summary: "แจ้งเตือนเครื่องซัก–อบ ตรวจสลิป และสะสมแต้มผ่าน LINE",
    category: "ระบบ",
    year: "LINE OA",
    role: "ทำระบบคนเดียว",
    accent: "#fb923c",
    accent2: "#facc15",
    visual: "tiger",
    highlights: ["แจ้งเตือนสถานะเครื่อง", "ตรวจสลิป", "ระบบสมาชิกและแต้ม"],
    images: [
      "/portfolio/tiger/chat-1.webp",
      "/portfolio/tiger/chat-2.webp",
      "/portfolio/tiger/chat-3.webp",
      "/portfolio/tiger/chat-4.webp",
      "/portfolio/tiger/chat-5.webp",
    ],
    links: [{ label: "เปิด LINE TigerLaundry", href: "https://line.me/R/ti/p/@396vuvgj" }],
    featured: true,
  },
  {
    slug: "cocolove",
    title: "COCOLOVE",
    eyebrow: "Operations & Media",
    summary: "ดูแลผู้สมัครกว่า 350 ทีม พร้อมจัดการสื่อและตัดต่อเบื้องหลังงาน",
    category: "ข้อมูล",
    year: "350+ ทีม",
    role: "ดูแลหลังบ้านและสื่อคนเดียว",
    accent: "#f472b6",
    accent2: "#a78bfa",
    visual: "cocolove",
    highlights: ["จัดการข้อมูลผู้สมัคร", "ตรวจสอบความครบถ้วน", "ตัดต่อและจัดการสื่อ"],
    images: [
      "/portfolio/cocolove/assets.webp",
      "/portfolio/cocolove/stage.webp",
      "/portfolio/cocolove/editing.webp",
      "/portfolio/cocolove/team.webp",
    ],
    links: [{ label: "ดู MG.KU.CSC × Coco Love Challenge", href: "https://www.facebook.com/profile.php?id=61583725063210" }],
  },
  {
    slug: "faculty-tutor",
    title: "ติวเตอร์ประจำคณะ",
    eyebrow: "Business Statistics & Accounting",
    summary: "เปลี่ยนวิชาที่ดูยาก ให้รุ่นน้องเห็นภาพและกล้าทำโจทย์มากขึ้น",
    category: "ข้อมูล",
    year: "20+ คน",
    role: "เตรียมและสอนคนเดียว",
    accent: "#38bdf8",
    accent2: "#2dd4bf",
    visual: "tutor",
    highlights: ["ติวสถิติทางธุรกิจ", "ติวบัญชีการเงินให้น้องปี 1", "สอนเดี่ยวกว่า 20 คน ขณะเรียนปี 2"],
    images: [
      "/portfolio/tutor/business-statistics-1.webp",
      "/portfolio/tutor/business-statistics-2.webp",
    ],
    links: [{ label: "ดูสื่อการติวบัญชีการเงิน", href: "https://canva.link/2aroqaurh446q8g" }],
  },
  {
    slug: "graphic-design",
    title: "Graphic Design",
    eyebrow: "Presentation · Event · Visual",
    summary: "ออกแบบงานหลายรูปแบบ ตั้งแต่ Presentation เสื้อกิจกรรม ไปจนถึงสื่อสัมมนา",
    category: "ครีเอทีฟ",
    year: "SOLO",
    role: "ออกแบบกราฟิกคนเดียว",
    accent: "#c084fc",
    accent2: "#f97316",
    visual: "freelance",
    highlights: ["Presentation Design: Starbucks", "กราฟิกสัมมนา Entrepreneur and New Venture ปี 3", "เสื้อกิจกรรม Yearbook แผนที่ 3D และสื่อประชาสัมพันธ์"],
    images: [
      "/portfolio/design/starbucks.webp",
      "/portfolio/design/next-gen.webp",
      "/portfolio/design/shirt-mockup.webp",
      "/portfolio/design/shirt-design.webp",
      "/portfolio/design/shirt-layout.webp",
      "/portfolio/design/yearbook.webp",
      "/portfolio/design/map-3d.webp",
      "/portfolio/design/billing-poster.webp",
      "/portfolio/design/photoshop.webp",
    ],
    links: [{ label: "ดูกราฟิกงานสัมมนา", href: "https://canva.link/veawj6m0by3fpfu" }],
  },
  {
    slug: "tiktok-creator",
    title: "TikTok Creator",
    eyebrow: "Idea to Content",
    summary: "เมื่อมีไอเดียที่อยากลอง ผมจะเปลี่ยนมันให้กลายเป็นคอนเทนต์แล้วปล่อยให้ผลตอบรับสอนผมต่อ",
    category: "ครีเอทีฟ",
    year: "OWN CHANNEL",
    role: "คิดและทำคอนเทนต์ช่องตัวเอง",
    accent: "#ff245f",
    accent2: "#25f4ee",
    visual: "creator",
    highlights: ["คิดหัวข้อจากสิ่งรอบตัว", "ทดลองรูปแบบคอนเทนต์", "เรียนรู้จากผลตอบรับจริง"],
    images: ["/portfolio/content/tiktok-profile.webp"],
  },
  {
    slug: "content-production",
    title: "Content Production",
    eyebrow: "Behind the Channel",
    summary: "ดูแลคอนเทนต์ให้ช่องของพี่สาว ตั้งแต่ไอเดียจนถึงวิดีโอที่พร้อมเผยแพร่",
    category: "ครีเอทีฟ",
    year: "FULL PROCESS",
    role: "Script · Camera · Edit · Advisor",
    accent: "#f43f5e",
    accent2: "#06b6d4",
    visual: "production",
    highlights: ["เขียนสคริปต์", "ถ่ายทำและเป็นตากล้อง", "ตัดต่อและให้คำปรึกษา"],
    images: ["/portfolio/content/production-work.webp"],
  },
  {
    slug: "fastwork-freelance",
    title: "Freelance Work",
    eyebrow: "งานจริง · ลูกค้าจริง",
    summary: "รับโจทย์หลากหลายผ่าน Fastwork และเปลี่ยนความต้องการให้เป็นชิ้นงาน",
    category: "ครีเอทีฟ",
    year: "Ongoing",
    role: "Freelancer",
    accent: "#c084fc",
    accent2: "#f97316",
    visual: "freelance",
    highlights: ["รับบรีฟ", "จัดลำดับงาน", "ส่งมอบตามเป้าหมาย"],
  },
  {
    slug: "wisdom-v-academy",
    title: "Wisdom V Academy",
    eyebrow: "Business Knowledge · Content",
    summary: "ถ่ายคอนเทนต์และถ่ายทอดความรู้ด้านธุรกิจให้น้อง ๆ มัธยมปลาย",
    category: "กิจกรรม",
    year: "KNOWLEDGE SHARING",
    role: "ถ่ายคอนเทนต์และให้ความรู้ด้านธุรกิจ",
    accent: "#f59e0b",
    accent2: "#3b82f6",
    visual: "activity",
    highlights: ["ถ่ายคอนเทนต์หน้างาน", "สื่อสารความรู้ด้านธุรกิจ", "ทำงานกับกลุ่มนักเรียนมัธยมปลาย"],
    images: [
      "/portfolio/activities/wisdom-v-1.webp",
      "/portfolio/activities/wisdom-v-2.webp",
    ],
  },
  {
    slug: "mechanical-learning",
    title: "เรียนรู้ข้ามศาสตร์",
    eyebrow: "Mechanical Engineering Elective",
    summary: "ลองออกจากสายบริหารไปเรียนรู้เครื่องกล ผ่านการลงมือทำและเครื่องมือจริง",
    category: "กิจกรรม",
    year: "OPEN MINDSET",
    role: "เรียนเสรีร่วมกับวิศวกรรมเครื่องกล",
    accent: "#94a3b8",
    accent2: "#f97316",
    visual: "activity",
    highlights: ["ทดลองใช้เครื่องกลึงเหล็ก", "เรียนรู้การเชื่อมเหล็ก", "เปิดประสบการณ์ด้าน CAD"],
    images: ["/portfolio/activities/mechanical-learning.webp"],
  },
  {
    slug: "campus-activities",
    title: "Campus Activities",
    eyebrow: "พิธีกร · สันทนาการ",
    summary: "อีกด้านของผมที่ได้พูดต่อหน้าคน ทำงานกับทีม และสร้างบรรยากาศ",
    category: "กิจกรรม",
    year: "KU CSC",
    role: "พิธีกรและฝ่ายสันทนาการ",
    accent: "#fb7185",
    accent2: "#fbbf24",
    visual: "activity",
    highlights: ["สื่อสารต่อหน้าคน", "ทำงานเป็นทีม", "แก้สถานการณ์เฉพาะหน้า"],
  },
];

export const skillGroups = [
  {
    name: "Graphic & Motion",
    color: "#ff4ecd",
    note: "จากไอเดียไปสู่ภาพที่สื่อสารได้",
    tools: ["Canva", "Premiere Pro", "Photoshop", "After Effects"],
  },
  {
    name: "Code & AI Workflow",
    color: "#55d6ff",
    note: "ใช้เครื่องมือหลายแบบเพื่อพาระบบไปถึงจุดที่ใช้งานได้",
    tools: ["Cursor", "Antigravity", "Obsidian", "Apps Script", "Hermes", "Claude Code", "Codex"],
  },
  {
    name: "Cyber Security",
    color: "#a8ff60",
    note: "สนใจมองระบบจากมุมของความเสี่ยงและการป้องกัน",
    tools: ["Burp Suite", "Kali Linux", "GitHub Tools", "OWASP ZAP"],
  },
  {
    name: "Digital Operations",
    color: "#ffb84d",
    note: "เครื่องมือประจำวันสำหรับจัดการงานและสื่อสาร",
    tools: ["LINE OA", "Excel", "OBS", "Word", "Microsoft Teams"],
  },
];

export const navItems = [
  { href: "/", label: "หน้าแรก" },
  { href: "/work", label: "ผลงาน" },
  { href: "/about", label: "ตัวผม" },
  { href: "/contact", label: "ติดต่อ" },
];
